### ISSUE TITLE
Error updating webhooks

### ISSUE THREAD

**Issue by TonyFleisher** [lnjustin/Rachio-Community#2]
Two different errors I ran into here that both produce: webhookHttp Exception Error: Internal Server Error

1. I had some old webhooks from a SmartThings setup that didn't get deleted properly.
2. After the first initialization, I was seeing this on every update.

Analysis:
1. If there are webhooks, but none that are for the app, getWebhookIdsForDev returns an empty list
2. After the webhook is setup, getWebhookIdsForDev returns a list with one entry

In initWebhooks()
```
def cmdType = webhookIds == null ? "post" : "put"
```
This will return put for case 1 above, but we should use post.

also in initWebhooks()
```
    if(!webhookIds) { 
        bodyData = new JsonOutput().toJson([device:[id: controlId], externalId: app.name, url: endpointUrl, eventTypes: webhookEvtTypes()])
    } else { 
        bodyData = new JsonOutput().toJson([id: webhookIds, externalId: app.name, url: endpointUrl, eventTypes: webhookEvtTypes()])
    }
```
If webhookIds is not null, the list (webhookids) is sent as the id parameter, but the API expects a string here (e.g. webhookids[0]).

**Comment by lnjustin** [comment]
Just seeing this. Could you send me a pull request for the proposed fix?
